version: "3.7"

services:

  kibana:
    container_name: kibana
    image: simbam1/kibana:1.0.2
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: install/docker/kibana/kibana.Dockerfile
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    ports:
      - 5601:5601
    restart: always
    volumes:
      - kibana-conf:/usr/share/kibana/data
    networks:
      - gtas-webapp-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: simbam1/elasticsearch:1.1.5
    container_name: elasticsearch
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: install/docker/elasticsearch/elasticsearch.Dockerfile
    ports:
      - 9300:9300
      - 9200:9200
    restart: always
    volumes: 
      - es-data:/usr/share/elasticsearch/data
      - elasticsearch-conf:/usr/share/elasticsearch/config
    networks: 
      - gtas-webapp-network

  logstash:
    image: simbam1/logstash:1.0.1
    container_name: logstash
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: ./install/docker/logstash/logstash.Dockerfile
    environment: 
      MARIADB_HOST: 'mariadb'
      ELASTIC_HOST: 'https://elasticsearch'
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: 'elasticsearch'
      LOGSTASH_KEYSTORE_PASS: admin123
    restart: always
    secrets:
      - elastic-ca
    networks:
      - gtas-webapp-network
    volumes:
      - logstash-conf:/usr/share/logstash/config/
    depends_on:
      - elasticsearch

  elk-setup:
    image: simbam1/elk-setup:1.1.2
    container_name: elk-setup
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: ./install/docker/elk-setup/elk-setup.Dockerfile
    environment:
      KIBANA_HOST: 'kibana'
      ELASTICSEARCH_HOST: 'elasticsearch'
    volumes:
      - logstash-conf:/logstash-conf
      - kibana-conf:/kibana-conf
      - elasticsearch-conf:/elasticsearch-conf
    secrets:
      - logstash-keystore-password
      - mysql-logstash-user
      - mysql-logstash-password
      - elastic-password
      - elasticsearch-kibana-user
      - elasticsearch-kibana-password
      - elastic-bootstrap-password
    networks:
      - gtas-webapp-network


secrets:
  logstash-keystore-password:
    file: ./gtas-parent/gtas-commons/secrets/logstash-keystore-password
  mysql-logstash-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql-logstash-user
  mysql-logstash-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql-logstash-password
  elastic-password:
    file: ./gtas-parent/gtas-commons/secrets/elastic-password
  elasticsearch-kibana-user:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-kibana-user
  elasticsearch-kibana-password:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-kibana-password
  elastic-bootstrap-password:
    file: ./gtas-parent/gtas-commons/secrets/elastic-bootstrap-password
  elastic-ca:
    file: ./gtas-parent/gtas-commons/certs/elastic-ca.crt

volumes:
  logstash-conf:
  kibana-conf:
  elasticsearch-conf:
  es-data:

networks:
  gtas-webapp-network:
    attachable: true