version: '3.7'
services:
  http-proxy:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-webapp-node
  web-app:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_HOME: "/usr/local/gtas-java-jre"
      JAVA_OPTS: "-Xms4g -Xmx8g -XX:MaxPermSize=16g -Duser.timezone=GMT"
      PROXY_IP: ""
    volumes:
      - type: bind
        source: /mnt/gtas-java-jre
        target: /usr/local/gtas-java-jre
      - type: bind
        source: /var/opt/gtas_web_app_application_properties
        target: /usr/local/tomcat/conf
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-webapp-node
  gtas-scheduler:
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport"
      JAVA_HOME: "/usr/local/gtas-java-jre"
      JAVA_OPTS: "-Xms8000m -Xmx16000m -Duser.timezone=UTC -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
    volumes:
      - type: bind
        source: /mnt/gtas-java-jre
        target: /usr/local/gtas-java-jre
      - type: bind
        source: /var/opt/gtas_scheduler_application_properties
        target: /usr/local/tomcat/conf
      - type: bind
        source: /mnt
        target: /usr/local/gtas-data
        consistency: consistent
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-messenger-node
  activemq:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-neo4j-node
  mariadb:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-db-node
  kibana:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  logstash:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  elk-setup:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-elk-node
  neo4j:
    deploy:
      placement:
        constraints:
          - node.hostname == gtas-neo4j-node

networks:
  GTAS_webapp-network:
    driver: "overlay"
    attachable: true