server.host: kibana.local
server.name: kibana
server.ssl.enabled: true
server.ssl.certificate: /etc/kibana/config/kibana.crt
server.ssl.key: /etc/kibana/config/kibana.key
elasticsearch.ssl.verificationMode: none
elasticsearch.ssl.certificateAuthorities: /etc/kibana/config/ca.crt
xpack.monitoring.elasticsearch.ssl.certificateAuthorities: /etc/kibana/config/ca.crt
elasticsearch.requestHeadersWhitelist: [ "Authorization", "x-forwarded-port", "x-forwarded-for", "x-proxy-user", "x-proxy-roles" ]
