# Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "https://${ELASTICSEARCH_HOST}:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true