version: "3.5"

services:
  neo4j-scheduler:
    build:
      context: ../gtas-neo4j-scheduler
    image: neo4j-scheduler
    container_name: neo4j-scheduler 
    volumes:
      - target:/root/.m2/
      - ../gtas-neo4j-scheduler:/etl-project:cached
  neo4j:
    build:
      context: .
      dockerfile: ./neo4j.Dockerfile
    container_name: neo4j
    image: gtas-neo4j
    ports:
      - 7474:7474   
      - 7687:7687
    networks: 
    - gtas_default
  etl-job:
    build:
      context: .
      dockerfile: ./etl_job.Dockerfile
    container_name: etl-job
    image: neo4j-etl-job
    networks: 
    - gtas_default
    depends_on: 
      - neo4j
      - mariahost
      - neo4j-scheduler
    volumes:
      - target:/root/.m2/

  mariahost:
    build:
      context: ../
      dockerfile: docker/db.Dockerfile
    ports:
      - "3306:3306"
    container_name: mariahost
    command: [
            '--wait_timeout=28800',
        ]
    networks: 
      - gtas_default
    volumes: 
      - db-data:/var/lib/mysql

  gtas-scheduler:
    container_name: gtas-scheduler
    build:
      context: ../
      dockerfile: gtas-parent/gtas-job-scheduler-war/Dockerfile
      args: 
        DB_HOST: 'mariahost'
        DB_USERNAME: 'root'
        DB_PASSWORD:  'admin'
    image: gtas-scheduler      
    environment:
      LOCAL_DRIVE_MAPPING_INPUT: ${LOCAL_DRIVE_MAPPING_INPUT}
      LOCAL_DRIVE_MAPPING_OUTPUT: ${LOCAL_DRIVE_MAPPING_OUTPUT}
    volumes:
      - ${LOCAL_DRIVE_MAPPING_INPUT}:/usr/local/input:rw
      - ${LOCAL_DRIVE_MAPPING_OUTPUT}:/usr/local/output:rw
      - data:/root/.m2
    networks:
      - gtas_default
    depends_on: 
      - mariahost
      - activemq
  builder: 
    container_name: gtas-builder 
    build: 
      context: ../
      dockerfile: docker/maven.Dockerfile
    image: gtas-builder
    depends_on: 
      - mariahost
    volumes:
      - data:/root/.m2/
      - ../gtas-parent:/project:cached

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - 61616:61616
      - 8161:8161
    networks: 
      - gtas_default

networks:
  gtas_default:
    driver: "bridge"
    name: gtas_default
volumes:
  target:
    driver: local 
  data:
    driver: local 
  db-data:
    driver: local
  